/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.univ.nantes.master.dsl.ui.AbstractAgendaUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AgendaUiModule extends AbstractAgendaUiModule {
  public AgendaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
