/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl;

import org.xtext.univ.nantes.master.dsl.AgendaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AgendaStandaloneSetup extends AgendaStandaloneSetupGenerated {
  public static void doSetup() {
    AgendaStandaloneSetup _agendaStandaloneSetup = new AgendaStandaloneSetup();
    _agendaStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
