/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl;

import org.xtext.univ.nantes.master.dsl.AbstractAgendaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AgendaRuntimeModule extends AbstractAgendaRuntimeModule {
}
