/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.agenda.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.univ.nantes.master.dsl.agenda.AgendaFactory;
import org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class AgendaPackageImpl extends EPackageImpl implements AgendaPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass agendaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass preambuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass contenuEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass descriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass eventS_OR_TASKSEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass eventEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass contenT_EVENTEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass taskEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private AgendaPackageImpl()
  {
    super(eNS_URI, AgendaFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link AgendaPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static AgendaPackage init()
  {
    if (isInited) return (AgendaPackage)EPackage.Registry.INSTANCE.getEPackage(AgendaPackage.eNS_URI);

    // Obtain or create and register package
    AgendaPackageImpl theAgendaPackage = (AgendaPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof AgendaPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new AgendaPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theAgendaPackage.createPackageContents();

    // Initialize created meta-data
    theAgendaPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theAgendaPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(AgendaPackage.eNS_URI, theAgendaPackage);
    return theAgendaPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAGENDA()
  {
    return agendaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAGENDA_Pream()
  {
    return (EReference)agendaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAGENDA_Contenu()
  {
    return (EReference)agendaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPREAMBULE()
  {
    return preambuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPREAMBULE_Name()
  {
    return (EAttribute)preambuleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCONTENU()
  {
    return contenuEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCONTENU_Desc()
  {
    return (EReference)contenuEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCONTENU_Evta()
  {
    return (EReference)contenuEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDESCRIPTION()
  {
    return descriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDESCRIPTION_Description()
  {
    return (EAttribute)descriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEVENTS_OR_TASKS()
  {
    return eventS_OR_TASKSEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEVENTS_OR_TASKS_Event_or_task()
  {
    return (EReference)eventS_OR_TASKSEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEVENT()
  {
    return eventEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEVENT_Name()
  {
    return (EAttribute)eventEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEVENT_Content_event()
  {
    return (EReference)eventEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCONTENT_EVENT()
  {
    return contenT_EVENTEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCONTENT_EVENT_Place()
  {
    return (EAttribute)contenT_EVENTEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCONTENT_EVENT_Data()
  {
    return (EAttribute)contenT_EVENTEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCONTENT_EVENT_Start()
  {
    return (EAttribute)contenT_EVENTEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCONTENT_EVENT_End()
  {
    return (EAttribute)contenT_EVENTEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTASK()
  {
    return taskEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTASK_Name()
  {
    return (EAttribute)taskEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTASK_NameEvent()
  {
    return (EReference)taskEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTASK_Deadline()
  {
    return (EAttribute)taskEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AgendaFactory getAgendaFactory()
  {
    return (AgendaFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    agendaEClass = createEClass(AGENDA);
    createEReference(agendaEClass, AGENDA__PREAM);
    createEReference(agendaEClass, AGENDA__CONTENU);

    preambuleEClass = createEClass(PREAMBULE);
    createEAttribute(preambuleEClass, PREAMBULE__NAME);

    contenuEClass = createEClass(CONTENU);
    createEReference(contenuEClass, CONTENU__DESC);
    createEReference(contenuEClass, CONTENU__EVTA);

    descriptionEClass = createEClass(DESCRIPTION);
    createEAttribute(descriptionEClass, DESCRIPTION__DESCRIPTION);

    eventS_OR_TASKSEClass = createEClass(EVENTS_OR_TASKS);
    createEReference(eventS_OR_TASKSEClass, EVENTS_OR_TASKS__EVENT_OR_TASK);

    eventEClass = createEClass(EVENT);
    createEAttribute(eventEClass, EVENT__NAME);
    createEReference(eventEClass, EVENT__CONTENT_EVENT);

    contenT_EVENTEClass = createEClass(CONTENT_EVENT);
    createEAttribute(contenT_EVENTEClass, CONTENT_EVENT__PLACE);
    createEAttribute(contenT_EVENTEClass, CONTENT_EVENT__DATA);
    createEAttribute(contenT_EVENTEClass, CONTENT_EVENT__START);
    createEAttribute(contenT_EVENTEClass, CONTENT_EVENT__END);

    taskEClass = createEClass(TASK);
    createEAttribute(taskEClass, TASK__NAME);
    createEReference(taskEClass, TASK__NAME_EVENT);
    createEAttribute(taskEClass, TASK__DEADLINE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    taskEClass.getESuperTypes().add(this.getEVENTS_OR_TASKS());

    // Initialize classes and features; add operations and parameters
    initEClass(agendaEClass, org.xtext.univ.nantes.master.dsl.agenda.AGENDA.class, "AGENDA", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAGENDA_Pream(), this.getPREAMBULE(), null, "pream", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.AGENDA.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAGENDA_Contenu(), this.getCONTENU(), null, "contenu", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.AGENDA.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(preambuleEClass, org.xtext.univ.nantes.master.dsl.agenda.PREAMBULE.class, "PREAMBULE", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPREAMBULE_Name(), ecorePackage.getEString(), "name", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.PREAMBULE.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(contenuEClass, org.xtext.univ.nantes.master.dsl.agenda.CONTENU.class, "CONTENU", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCONTENU_Desc(), this.getDESCRIPTION(), null, "desc", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.CONTENU.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCONTENU_Evta(), this.getEVENTS_OR_TASKS(), null, "evta", null, 0, -1, org.xtext.univ.nantes.master.dsl.agenda.CONTENU.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(descriptionEClass, org.xtext.univ.nantes.master.dsl.agenda.DESCRIPTION.class, "DESCRIPTION", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDESCRIPTION_Description(), ecorePackage.getEString(), "description", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.DESCRIPTION.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(eventS_OR_TASKSEClass, org.xtext.univ.nantes.master.dsl.agenda.EVENTS_OR_TASKS.class, "EVENTS_OR_TASKS", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEVENTS_OR_TASKS_Event_or_task(), this.getEVENT(), null, "event_or_task", null, 0, -1, org.xtext.univ.nantes.master.dsl.agenda.EVENTS_OR_TASKS.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(eventEClass, org.xtext.univ.nantes.master.dsl.agenda.EVENT.class, "EVENT", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEVENT_Name(), ecorePackage.getEString(), "name", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.EVENT.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEVENT_Content_event(), this.getCONTENT_EVENT(), null, "content_event", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.EVENT.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(contenT_EVENTEClass, org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT.class, "CONTENT_EVENT", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCONTENT_EVENT_Place(), ecorePackage.getEString(), "place", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCONTENT_EVENT_Data(), ecorePackage.getEString(), "data", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCONTENT_EVENT_Start(), ecorePackage.getEString(), "start", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCONTENT_EVENT_End(), ecorePackage.getEString(), "end", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(taskEClass, org.xtext.univ.nantes.master.dsl.agenda.TASK.class, "TASK", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTASK_Name(), ecorePackage.getEString(), "name", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.TASK.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTASK_NameEvent(), this.getEVENT(), null, "nameEvent", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.TASK.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTASK_Deadline(), ecorePackage.getEString(), "deadline", null, 0, 1, org.xtext.univ.nantes.master.dsl.agenda.TASK.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //AgendaPackageImpl
