/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.scoping;

import org.xtext.univ.nantes.master.dsl.scoping.AbstractAgendaScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class AgendaScopeProvider extends AbstractAgendaScopeProvider {
}
