/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.agenda;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage
 * @generated
 */
public interface AgendaFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AgendaFactory eINSTANCE = org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaFactoryImpl.init();

  /**
   * Returns a new object of class '<em>AGENDA</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AGENDA</em>'.
   * @generated
   */
  AGENDA createAGENDA();

  /**
   * Returns a new object of class '<em>PREAMBULE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PREAMBULE</em>'.
   * @generated
   */
  PREAMBULE createPREAMBULE();

  /**
   * Returns a new object of class '<em>CONTENU</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CONTENU</em>'.
   * @generated
   */
  CONTENU createCONTENU();

  /**
   * Returns a new object of class '<em>DESCRIPTION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DESCRIPTION</em>'.
   * @generated
   */
  DESCRIPTION createDESCRIPTION();

  /**
   * Returns a new object of class '<em>EVENTS OR TASKS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EVENTS OR TASKS</em>'.
   * @generated
   */
  EVENTS_OR_TASKS createEVENTS_OR_TASKS();

  /**
   * Returns a new object of class '<em>EVENT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EVENT</em>'.
   * @generated
   */
  EVENT createEVENT();

  /**
   * Returns a new object of class '<em>CONTENT EVENT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CONTENT EVENT</em>'.
   * @generated
   */
  CONTENT_EVENT createCONTENT_EVENT();

  /**
   * Returns a new object of class '<em>TASK</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TASK</em>'.
   * @generated
   */
  TASK createTASK();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AgendaPackage getAgendaPackage();

} //AgendaFactory
