/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.agenda;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaFactory
 * @model kind="package"
 * @generated
 */
public interface AgendaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "agenda";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/univ/nantes/master/dsl/Agenda";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "agenda";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AgendaPackage eINSTANCE = org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.univ.nantes.master.dsl.agenda.impl.MODELImpl <em>MODEL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.univ.nantes.master.dsl.agenda.impl.MODELImpl
   * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaPackageImpl#getMODEL()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Entite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ENTITE = 0;

  /**
   * The number of structural features of the '<em>MODEL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.univ.nantes.master.dsl.agenda.impl.TYPEImpl <em>TYPE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.univ.nantes.master.dsl.agenda.impl.TYPEImpl
   * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaPackageImpl#getTYPE()
   * @generated
   */
  int TYPE = 1;

  /**
   * The number of structural features of the '<em>TYPE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.univ.nantes.master.dsl.agenda.impl.AGENDAImpl <em>AGENDA</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AGENDAImpl
   * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaPackageImpl#getAGENDA()
   * @generated
   */
  int AGENDA = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENDA__NAME = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENDA__DESCRIPTION = TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Event</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENDA__EVENT = TYPE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Task</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENDA__TASK = TYPE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>AGENDA</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENDA_FEATURE_COUNT = TYPE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.univ.nantes.master.dsl.agenda.impl.EVENTImpl <em>EVENT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.univ.nantes.master.dsl.agenda.impl.EVENTImpl
   * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaPackageImpl#getEVENT()
   * @generated
   */
  int EVENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Place</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__PLACE = 1;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__DATE = 2;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__START = 3;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__END = 4;

  /**
   * The number of structural features of the '<em>EVENT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.univ.nantes.master.dsl.agenda.impl.TASKImpl <em>TASK</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.univ.nantes.master.dsl.agenda.impl.TASKImpl
   * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaPackageImpl#getTASK()
   * @generated
   */
  int TASK = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Ref Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__REF_EVENT = 1;

  /**
   * The feature id for the '<em><b>Deadline</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DEADLINE = 2;

  /**
   * The number of structural features of the '<em>TASK</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.univ.nantes.master.dsl.agenda.MODEL <em>MODEL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MODEL</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.MODEL
   * @generated
   */
  EClass getMODEL();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.univ.nantes.master.dsl.agenda.MODEL#getEntite <em>Entite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Entite</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.MODEL#getEntite()
   * @see #getMODEL()
   * @generated
   */
  EReference getMODEL_Entite();

  /**
   * Returns the meta object for class '{@link org.xtext.univ.nantes.master.dsl.agenda.TYPE <em>TYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TYPE</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.TYPE
   * @generated
   */
  EClass getTYPE();

  /**
   * Returns the meta object for class '{@link org.xtext.univ.nantes.master.dsl.agenda.AGENDA <em>AGENDA</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AGENDA</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.AGENDA
   * @generated
   */
  EClass getAGENDA();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getName()
   * @see #getAGENDA()
   * @generated
   */
  EAttribute getAGENDA_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getDescription()
   * @see #getAGENDA()
   * @generated
   */
  EAttribute getAGENDA_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Event</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getEvent()
   * @see #getAGENDA()
   * @generated
   */
  EReference getAGENDA_Event();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getTask <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Task</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getTask()
   * @see #getAGENDA()
   * @generated
   */
  EReference getAGENDA_Task();

  /**
   * Returns the meta object for class '{@link org.xtext.univ.nantes.master.dsl.agenda.EVENT <em>EVENT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EVENT</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.EVENT
   * @generated
   */
  EClass getEVENT();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.univ.nantes.master.dsl.agenda.EVENT#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.EVENT#getName()
   * @see #getEVENT()
   * @generated
   */
  EAttribute getEVENT_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.univ.nantes.master.dsl.agenda.EVENT#getPlace <em>Place</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Place</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.EVENT#getPlace()
   * @see #getEVENT()
   * @generated
   */
  EAttribute getEVENT_Place();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.univ.nantes.master.dsl.agenda.EVENT#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.EVENT#getDate()
   * @see #getEVENT()
   * @generated
   */
  EAttribute getEVENT_Date();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.univ.nantes.master.dsl.agenda.EVENT#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.EVENT#getStart()
   * @see #getEVENT()
   * @generated
   */
  EAttribute getEVENT_Start();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.univ.nantes.master.dsl.agenda.EVENT#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.EVENT#getEnd()
   * @see #getEVENT()
   * @generated
   */
  EAttribute getEVENT_End();

  /**
   * Returns the meta object for class '{@link org.xtext.univ.nantes.master.dsl.agenda.TASK <em>TASK</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TASK</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.TASK
   * @generated
   */
  EClass getTASK();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.univ.nantes.master.dsl.agenda.TASK#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.TASK#getName()
   * @see #getTASK()
   * @generated
   */
  EAttribute getTASK_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.univ.nantes.master.dsl.agenda.TASK#getRefEvent <em>Ref Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref Event</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.TASK#getRefEvent()
   * @see #getTASK()
   * @generated
   */
  EReference getTASK_RefEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.univ.nantes.master.dsl.agenda.TASK#getDeadline <em>Deadline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Deadline</em>'.
   * @see org.xtext.univ.nantes.master.dsl.agenda.TASK#getDeadline()
   * @see #getTASK()
   * @generated
   */
  EAttribute getTASK_Deadline();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AgendaFactory getAgendaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.univ.nantes.master.dsl.agenda.impl.MODELImpl <em>MODEL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.univ.nantes.master.dsl.agenda.impl.MODELImpl
     * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaPackageImpl#getMODEL()
     * @generated
     */
    EClass MODEL = eINSTANCE.getMODEL();

    /**
     * The meta object literal for the '<em><b>Entite</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ENTITE = eINSTANCE.getMODEL_Entite();

    /**
     * The meta object literal for the '{@link org.xtext.univ.nantes.master.dsl.agenda.impl.TYPEImpl <em>TYPE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.univ.nantes.master.dsl.agenda.impl.TYPEImpl
     * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaPackageImpl#getTYPE()
     * @generated
     */
    EClass TYPE = eINSTANCE.getTYPE();

    /**
     * The meta object literal for the '{@link org.xtext.univ.nantes.master.dsl.agenda.impl.AGENDAImpl <em>AGENDA</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AGENDAImpl
     * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaPackageImpl#getAGENDA()
     * @generated
     */
    EClass AGENDA = eINSTANCE.getAGENDA();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGENDA__NAME = eINSTANCE.getAGENDA_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGENDA__DESCRIPTION = eINSTANCE.getAGENDA_Description();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGENDA__EVENT = eINSTANCE.getAGENDA_Event();

    /**
     * The meta object literal for the '<em><b>Task</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGENDA__TASK = eINSTANCE.getAGENDA_Task();

    /**
     * The meta object literal for the '{@link org.xtext.univ.nantes.master.dsl.agenda.impl.EVENTImpl <em>EVENT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.univ.nantes.master.dsl.agenda.impl.EVENTImpl
     * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaPackageImpl#getEVENT()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEVENT();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEVENT_Name();

    /**
     * The meta object literal for the '<em><b>Place</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__PLACE = eINSTANCE.getEVENT_Place();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__DATE = eINSTANCE.getEVENT_Date();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__START = eINSTANCE.getEVENT_Start();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__END = eINSTANCE.getEVENT_End();

    /**
     * The meta object literal for the '{@link org.xtext.univ.nantes.master.dsl.agenda.impl.TASKImpl <em>TASK</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.univ.nantes.master.dsl.agenda.impl.TASKImpl
     * @see org.xtext.univ.nantes.master.dsl.agenda.impl.AgendaPackageImpl#getTASK()
     * @generated
     */
    EClass TASK = eINSTANCE.getTASK();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTASK_Name();

    /**
     * The meta object literal for the '<em><b>Ref Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__REF_EVENT = eINSTANCE.getTASK_RefEvent();

    /**
     * The meta object literal for the '<em><b>Deadline</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__DEADLINE = eINSTANCE.getTASK_Deadline();

  }

} //AgendaPackage
