/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.agenda;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AGENDA</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getPream <em>Pream</em>}</li>
 *   <li>{@link org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getContenu <em>Contenu</em>}</li>
 * </ul>
 *
 * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getAGENDA()
 * @model
 * @generated
 */
public interface AGENDA extends EObject
{
  /**
   * Returns the value of the '<em><b>Pream</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pream</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pream</em>' containment reference.
   * @see #setPream(PREAMBULE)
   * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getAGENDA_Pream()
   * @model containment="true"
   * @generated
   */
  PREAMBULE getPream();

  /**
   * Sets the value of the '{@link org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getPream <em>Pream</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pream</em>' containment reference.
   * @see #getPream()
   * @generated
   */
  void setPream(PREAMBULE value);

  /**
   * Returns the value of the '<em><b>Contenu</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contenu</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contenu</em>' containment reference.
   * @see #setContenu(CONTENU)
   * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getAGENDA_Contenu()
   * @model containment="true"
   * @generated
   */
  CONTENU getContenu();

  /**
   * Sets the value of the '{@link org.xtext.univ.nantes.master.dsl.agenda.AGENDA#getContenu <em>Contenu</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contenu</em>' containment reference.
   * @see #getContenu()
   * @generated
   */
  void setContenu(CONTENU value);

} // AGENDA
