/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.agenda;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CONTENT EVENT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT#getPlace <em>Place</em>}</li>
 *   <li>{@link org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT#getData <em>Data</em>}</li>
 *   <li>{@link org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT#getStart <em>Start</em>}</li>
 *   <li>{@link org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getCONTENT_EVENT()
 * @model
 * @generated
 */
public interface CONTENT_EVENT extends EObject
{
  /**
   * Returns the value of the '<em><b>Place</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Place</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Place</em>' attribute.
   * @see #setPlace(String)
   * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getCONTENT_EVENT_Place()
   * @model
   * @generated
   */
  String getPlace();

  /**
   * Sets the value of the '{@link org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT#getPlace <em>Place</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Place</em>' attribute.
   * @see #getPlace()
   * @generated
   */
  void setPlace(String value);

  /**
   * Returns the value of the '<em><b>Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' attribute.
   * @see #setData(String)
   * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getCONTENT_EVENT_Data()
   * @model
   * @generated
   */
  String getData();

  /**
   * Sets the value of the '{@link org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT#getData <em>Data</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data</em>' attribute.
   * @see #getData()
   * @generated
   */
  void setData(String value);

  /**
   * Returns the value of the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Start</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' attribute.
   * @see #setStart(String)
   * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getCONTENT_EVENT_Start()
   * @model
   * @generated
   */
  String getStart();

  /**
   * Sets the value of the '{@link org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT#getStart <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' attribute.
   * @see #getStart()
   * @generated
   */
  void setStart(String value);

  /**
   * Returns the value of the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute.
   * @see #setEnd(String)
   * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getCONTENT_EVENT_End()
   * @model
   * @generated
   */
  String getEnd();

  /**
   * Sets the value of the '{@link org.xtext.univ.nantes.master.dsl.agenda.CONTENT_EVENT#getEnd <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' attribute.
   * @see #getEnd()
   * @generated
   */
  void setEnd(String value);

} // CONTENT_EVENT
