/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.agenda;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CONTENU</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.univ.nantes.master.dsl.agenda.CONTENU#getDesc <em>Desc</em>}</li>
 *   <li>{@link org.xtext.univ.nantes.master.dsl.agenda.CONTENU#getEvta <em>Evta</em>}</li>
 * </ul>
 *
 * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getCONTENU()
 * @model
 * @generated
 */
public interface CONTENU extends EObject
{
  /**
   * Returns the value of the '<em><b>Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Desc</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Desc</em>' containment reference.
   * @see #setDesc(DESCRIPTION)
   * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getCONTENU_Desc()
   * @model containment="true"
   * @generated
   */
  DESCRIPTION getDesc();

  /**
   * Sets the value of the '{@link org.xtext.univ.nantes.master.dsl.agenda.CONTENU#getDesc <em>Desc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Desc</em>' containment reference.
   * @see #getDesc()
   * @generated
   */
  void setDesc(DESCRIPTION value);

  /**
   * Returns the value of the '<em><b>Evta</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.univ.nantes.master.dsl.agenda.EVENTS_OR_TASKS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Evta</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evta</em>' containment reference list.
   * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getCONTENU_Evta()
   * @model containment="true"
   * @generated
   */
  EList<EVENTS_OR_TASKS> getEvta();

} // CONTENU
