/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.agenda;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EVENTS OR TASKS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.univ.nantes.master.dsl.agenda.EVENTS_OR_TASKS#getEvent_or_task <em>Event or task</em>}</li>
 * </ul>
 *
 * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getEVENTS_OR_TASKS()
 * @model
 * @generated
 */
public interface EVENTS_OR_TASKS extends EObject
{
  /**
   * Returns the value of the '<em><b>Event or task</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.univ.nantes.master.dsl.agenda.EVENT}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event or task</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event or task</em>' containment reference list.
   * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getEVENTS_OR_TASKS_Event_or_task()
   * @model containment="true"
   * @generated
   */
  EList<EVENT> getEvent_or_task();

} // EVENTS_OR_TASKS
