/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.agenda;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MODEL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.univ.nantes.master.dsl.agenda.MODEL#getEntite <em>Entite</em>}</li>
 * </ul>
 *
 * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getMODEL()
 * @model
 * @generated
 */
public interface MODEL extends EObject
{
  /**
   * Returns the value of the '<em><b>Entite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entite</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entite</em>' containment reference.
   * @see #setEntite(TYPE)
   * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getMODEL_Entite()
   * @model containment="true"
   * @generated
   */
  TYPE getEntite();

  /**
   * Sets the value of the '{@link org.xtext.univ.nantes.master.dsl.agenda.MODEL#getEntite <em>Entite</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entite</em>' containment reference.
   * @see #getEntite()
   * @generated
   */
  void setEntite(TYPE value);

} // MODEL
