/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.agenda;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TYPE</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage#getTYPE()
 * @model
 * @generated
 */
public interface TYPE extends EObject
{
} // TYPE
