/*
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.univ.nantes.master.dsl.parser.antlr.internal.InternalAgendaParser;
import org.xtext.univ.nantes.master.dsl.services.AgendaGrammarAccess;

public class AgendaParser extends AbstractAntlrParser {

	@Inject
	private AgendaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAgendaParser createParser(XtextTokenStream stream) {
		return new InternalAgendaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AGENDA";
	}

	public AgendaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AgendaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
