/*
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.univ.nantes.master.dsl.agenda.MODEL

@RunWith(XtextRunner)
@InjectWith(AgendaInjectorProvider)
class AgendaParsingTest{

	@Inject
	ParseHelper<MODEL> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
