/*
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.univ.nantes.master.dsl.ide.contentassist.antlr.internal.InternalAgendaParser;
import org.xtext.univ.nantes.master.dsl.services.AgendaGrammarAccess;

public class AgendaParser extends AbstractContentAssistParser {

	@Inject
	private AgendaGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalAgendaParser createParser() {
		InternalAgendaParser result = new InternalAgendaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAGENDAAccess().getGroup(), "rule__AGENDA__Group__0");
					put(grammarAccess.getEVENTAccess().getGroup(), "rule__EVENT__Group__0");
					put(grammarAccess.getTASKAccess().getGroup(), "rule__TASK__Group__0");
					put(grammarAccess.getTASKAccess().getGroup_2(), "rule__TASK__Group_2__0");
					put(grammarAccess.getMODELAccess().getEntiteAssignment(), "rule__MODEL__EntiteAssignment");
					put(grammarAccess.getAGENDAAccess().getNameAssignment_1(), "rule__AGENDA__NameAssignment_1");
					put(grammarAccess.getAGENDAAccess().getDescriptionAssignment_4(), "rule__AGENDA__DescriptionAssignment_4");
					put(grammarAccess.getAGENDAAccess().getEventAssignment_5(), "rule__AGENDA__EventAssignment_5");
					put(grammarAccess.getAGENDAAccess().getTaskAssignment_6(), "rule__AGENDA__TaskAssignment_6");
					put(grammarAccess.getEVENTAccess().getNameAssignment_1(), "rule__EVENT__NameAssignment_1");
					put(grammarAccess.getEVENTAccess().getPlaceAssignment_4(), "rule__EVENT__PlaceAssignment_4");
					put(grammarAccess.getEVENTAccess().getDateAssignment_6(), "rule__EVENT__DateAssignment_6");
					put(grammarAccess.getEVENTAccess().getStartAssignment_8(), "rule__EVENT__StartAssignment_8");
					put(grammarAccess.getEVENTAccess().getEndAssignment_10(), "rule__EVENT__EndAssignment_10");
					put(grammarAccess.getTASKAccess().getNameAssignment_1(), "rule__TASK__NameAssignment_1");
					put(grammarAccess.getTASKAccess().getRefEventAssignment_2_1(), "rule__TASK__RefEventAssignment_2_1");
					put(grammarAccess.getTASKAccess().getDeadlineAssignment_5(), "rule__TASK__DeadlineAssignment_5");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalAgendaParser typedParser = (InternalAgendaParser) parser;
			typedParser.entryRuleMODEL();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AgendaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AgendaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
