/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.ui.contentassist;

import org.xtext.univ.nantes.master.dsl.ui.contentassist.AbstractAgendaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AgendaProposalProvider extends AbstractAgendaProposalProvider {
}
