/*
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAgendaScopeProvider extends DelegatingScopeProvider {
}
