/*
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.univ.nantes.master.dsl.ui.internal.DslActivator;

public class AgendaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.xtext.univ.nantes.master.dsl.Agenda");
	}

}
