/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.agenda.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.univ.nantes.master.dsl.agenda.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.univ.nantes.master.dsl.agenda.AgendaPackage
 * @generated
 */
public class AgendaSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static AgendaPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AgendaSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = AgendaPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case AgendaPackage.AGENDA:
      {
        AGENDA agenda = (AGENDA)theEObject;
        T result = caseAGENDA(agenda);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AgendaPackage.PREAMBULE:
      {
        PREAMBULE preambule = (PREAMBULE)theEObject;
        T result = casePREAMBULE(preambule);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AgendaPackage.CONTENU:
      {
        CONTENU contenu = (CONTENU)theEObject;
        T result = caseCONTENU(contenu);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AgendaPackage.DESCRIPTION:
      {
        DESCRIPTION description = (DESCRIPTION)theEObject;
        T result = caseDESCRIPTION(description);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AgendaPackage.EVENTS_OR_TASKS:
      {
        EVENTS_OR_TASKS eventS_OR_TASKS = (EVENTS_OR_TASKS)theEObject;
        T result = caseEVENTS_OR_TASKS(eventS_OR_TASKS);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AgendaPackage.EVENT:
      {
        EVENT event = (EVENT)theEObject;
        T result = caseEVENT(event);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AgendaPackage.CONTENT_EVENT:
      {
        CONTENT_EVENT contenT_EVENT = (CONTENT_EVENT)theEObject;
        T result = caseCONTENT_EVENT(contenT_EVENT);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AgendaPackage.TASK:
      {
        TASK task = (TASK)theEObject;
        T result = caseTASK(task);
        if (result == null) result = caseEVENTS_OR_TASKS(task);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>AGENDA</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>AGENDA</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAGENDA(AGENDA object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>PREAMBULE</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>PREAMBULE</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePREAMBULE(PREAMBULE object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>CONTENU</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>CONTENU</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCONTENU(CONTENU object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>DESCRIPTION</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>DESCRIPTION</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDESCRIPTION(DESCRIPTION object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EVENTS OR TASKS</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EVENTS OR TASKS</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEVENTS_OR_TASKS(EVENTS_OR_TASKS object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EVENT</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EVENT</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEVENT(EVENT object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>CONTENT EVENT</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>CONTENT EVENT</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCONTENT_EVENT(CONTENT_EVENT object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>TASK</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>TASK</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTASK(TASK object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //AgendaSwitch
