/**
 * generated by Xtext 2.10.0
 */
package org.xtext.univ.nantes.master.dsl.validation;

import org.xtext.univ.nantes.master.dsl.validation.AbstractAgendaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AgendaValidator extends AbstractAgendaValidator {
}
